### ISSUE TITLE
Arrays of arrays causes failure in UDTCompiler

### ISSUE THREAD

**Issue by ritchiecarroll** [GridProtectionAlliance/openECA#1]
Right now when an array type is created in the UI and added to a new UDT, a separate array based type appears in the drop as an array, e.g., byte[].

If you now try to use this new type as an array the UDTCompiler throws an exception.

**Comment by StephenCWills** [comment]
We need to modify the UI to filter array types out of the dropdown.

**Comment by wbernest** [comment]
I just disabled the array check box if the user selects an array from the types list
