### ISSUE TITLE
Modify UserDefinedOutputMapping signals to be editable.

### ISSUE THREAD

**Issue by ritchiecarroll** [GridProtectionAlliance/openECA#15]
This is only applicable when adding a new mapping:

Once the "Add Signals" has been called, the device and associated measurements exist - so button should immediately change to "Edit Signals". For this to work, Javascript will need to load existing DeviceID and SignalID in order to "update" existing records - how about returning an updated MetaSignal from m_dataSubscriptionOperations.MetaSignalCommand(signal)?

Also, since there is a "Select" button already on the screen, if you are "editing" an existing mapping I would not show the "Add Signals" button in Edit mode for the output mapping.

**Comment by wbernest** [comment]
Fixed bug in the javascript
