### ISSUE TITLE
Array mapping with FILTER expression adds spurious semi-colon

### ISSUE THREAD

**Issue by ritchiecarroll** [GridProtectionAlliance/openECA#18]
Semi colon gets added to the end of the expression when mapping get written to a file - this causes a parsing error on load.

This only happens on Input Mappings, Output Mappings work fine.

![image](https://cloud.githubusercontent.com/assets/9202752/23261283/9a3c2db2-f9a3-11e6-8195-25419c3fe7b1.png)

Example filter expression against mappings:
`FILTER Mappings WHERE TypeCategory = 'ECA' AND TypeIdentifier = 'VIPair'`

**Comment by wbernest** [comment]
fixed bug in javascript
