### ISSUE TITLE
No validation for Mapping Identifier in Output Mappings page

### ISSUE THREAD

**Issue by chefsteph9** [GridProtectionAlliance/openECA#19]
When you are editing/adding a new "Output Mapping" There is no validation for the "Mapping Identifier" like there is when you are adding a new "Input Mapping".  

For example, if put a space in the name of an Output Mapping, you can still click the save button, after which it will fail to compile. 

If you try to do the same thing when adding an Input Mapping, the save button is disabled, preventing you from saving an invalid mapping identifier.

![image](https://cloud.githubusercontent.com/assets/19471558/23263487/64cf0bbe-f9ac-11e6-8332-dd5279ddbc23.png)

**Comment by wbernest** [comment]
accounted for whitespace in new enabler function
