### ISSUE TITLE
Time Window in new InputDataMapping in ModelingManager default to microsecond 

### ISSUE THREAD

**Issue by contributor51** [GridProtectionAlliance/openECA#31]
To reproduce, create a new input mapping, check the "Array" box, enter the text "last 1 second" in Time Window textbox, save the new input mapping. The time window defaults to last 1 microsecond.

**Comment by chefsteph9** [comment]
I think this issue was fixed when I fixed #30. Try pulling latest and let me know if you're still seeing this bug.

Thanks.

**Comment by contributor51** [comment]
This was fixed. Thank you.
