### ISSUE TITLE
Make using keywords in MappingIdentifier illiegal or add namespace.

### ISSUE THREAD

**Issue by kdjones** [GridProtectionAlliance/openECA#37]
You cant name a mapping identifier 'Output' because it conflicts with the internal class Output in Algorithm.cs. If you know what youre doing you can always add the namespace manually. However, you could make certain keywords illegal, or add the namespace automatically to prevent collision.

**Comment by kdjones** [comment]
Sorry... i think I actually meant the Identifier of the UDT, not th eMappingIdentifier.

**Comment by wbernest** [comment]
commit `b2f0fc3` Added an illegal identifier array for the Type Identifier.  Currently only has Output listed.
