### ISSUE TITLE
The given key was not present in the dictionary - SQLITE

### ISSUE THREAD

**Issue by Orlllem** [GridProtectionAlliance/openECA#48]
Hello, 

After building and compiling the newest master version. Then, adding a new device I get the following error.

[PMU_27] Attempting connection...
[PMU_27] Connection attempt failed: The given key was not present in the dictionary.
[PMU_27] Data channel user unhandled exception: The given key was not present in the dictionary.   

The PMU_27 is the device that I added.

![image](https://user-images.githubusercontent.com/53803049/104617501-45a69800-566a-11eb-9cc3-4b5397bc09ec.png)

Do you know anything that can be done?

Thanks,
Orlem

**Comment by ritchiecarroll** [comment]
Can you provide an associated error log? It will have a stack trace we can use to see where the error is being thrown?

**Comment by Orlllem** [comment]
Hello, thanks for fast response. The ErrorLog.txt and stack trace are below


---- Stack Trace ----
   System.ThrowHelper.ThrowKeyNotFoundException()
       openECA.exe: N 00038
   System.Collections.Generic.Dictionary`2.get_Item(key As TKey)
       openECA.exe: N 00054
   GSF.Communication.UdpClient.get_ServerUri()
       openECA.exe: N 00090
   GSF.PhasorProtocols.MultiProtocolFrameParser.get_ConnectionInfo()
       openECA.exe: N 00225
   PhasorProtocolAdapters.PhasorMeasurementMapper.get_ConnectionInfo()
       openECA.exe: N 00051
   PhasorProtocolAdapters.PhasorMeasurementMapper.m_frameParser_ConnectionAttempt(sender As Object, e As EventArgs)
       openECA.exe: N 00022
   GSF.Communication.ClientBase.OnConnectionAttempt()
       openECA.exe: N 00079

**Comment by ritchiecarroll** [comment]
OK, I've posted a fix for this, thanks for the catch:
https://github.com/GridProtectionAlliance/gsf/commit/cb2a454f803cfbccb7990a68dbf352d2ba2188c8

This should be available in an updated version of openECA after tonight's nightly build which starts building around midnight Eastern time.

Out of curiosity, can you share the connection string for the offending device connection? (Excluding IP for security reasons)

Thanks,
Ritchie

**Comment by Orlllem** [comment]
Thanks for the help, I appreciate

Sorry but what do you mean about connection string? 

you mean this
transportprotocol=Udp;localport=5785; interface=0.0.0.0
?

in which file can I see this connection string?

thanks, orlem

**Comment by clackner-gpa** [comment]
Yes someting like `transportprotocol=Udp;localport=5785; interface=0.0.0.0`. Every Device has a connection string associated with it. If you check in the Manager where you connected to your Device you can see it in the UI. It's saved in the DataBase not a specific File and determines the parameters (such as IP, Port etc) used to connect to the device. 
![image](https://user-images.githubusercontent.com/52460212/104702392-ee450e00-56e3-11eb-9487-7ea0e446f1ff.png)

**Comment by Orlllem** [comment]
Hi Christoph Lackner, 

So the connection string is the one that I displayed above:

transportprotocol=Udp;localport=5785; interface=0.0.0.0

![image](https://user-images.githubusercontent.com/53803049/104734061-6d573800-571e-11eb-8b9a-fe8fe9679b9c.png)


thanks, orlem

**Comment by Orlllem** [comment]
Thank you Ritchie and Christoph

It is working like a charm!!

![image](https://user-images.githubusercontent.com/53803049/104745647-1442d080-572d-11eb-99df-2c543fdd565a.png)

Thanks, orlem
